import { lstat, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dashboardCompatibilityMarker = "// Generated by scripts/run-tests.mjs from canonical dashboard modules.";
const dashboardAppSourceFiles = [
  "src/pages/dashboard/app-helpers.js",
  "src/pages/dashboard/app-state.js",
  "src/pages/dashboard/app-scratchpad.js",
  "src/pages/dashboard/app-communication.js",
  "src/pages/dashboard/app-render.js",
  "src/pages/dashboard/app-integrations.js",
  "src/pages/dashboard/app-actions.js",
  "src/pages/dashboard/app-sync.js",
  "src/pages/dashboard/app-bootstrap.js",
];

const compatibilityPaths = [
  ["index.html", "src/pages/dashboard/index.html"],
  ["app.js", "src/pages/dashboard/app.js"],
  ["styles.css", "src/pages/dashboard/styles.css"],
  ["login.html", "src/pages/login/index.html"],
  ["login.css", "src/pages/login/login.css"],
  ["sale-manager.html", "src/pages/sale/index.html"],
  ["sale-manager.js", "src/pages/sale/sale-manager.js"],
  ["sale-manager.css", "src/pages/sale/sale-manager.css"],
  ["room-summary.js", "src/pages/sale/room-summary.js"],
  ["room-summary.css", "src/pages/sale/room-summary.css"],
  ["sales-assistant.js", "src/features/sales/sales-assistant.js"],
  ["sales-assistant.css", "src/features/sales/sales-assistant.css"],
  ["sale-appointment.js", "src/features/sales/sale-appointment.js"],
  ["project-details.js", "src/features/project-details/project-details.js"],
  ["project-details.css", "src/features/project-details/project-details.css"],
  ["turtlebot4-art.webp", "src/features/project-details/turtlebot4-art.webp"],
  ["finance-demo.js", "src/features/finance/finance.js"],
  ["finance-demo.css", "src/features/finance/finance.css"],
  ["weather-rain.js", "src/features/weather/weather-rain.js"],
  ["todo-visibility.js", "src/features/tasks/todo-visibility.js"],
  ["task-english.js", "src/features/tasks/task-english.js"],
  ["task-reminders-events.js", "src/features/tasks/task-reminders-events.js"],
  ["task-reminders.js", "src/features/tasks/task-reminders.js"],
  ["task-reminders.css", "src/features/tasks/task-reminders.css"],
  ["auth-ui.js", "src/features/auth/auth-ui.js"],
  ["auth-ui.css", "src/features/auth/auth-ui.css"],
  ["push-notifications.js", "src/features/notifications/push-notifications.js"],
  ["mobile-notifications.css", "src/features/notifications/mobile-notifications.css"],
  ["weather-status-ui.js", "src/features/notifications/weather-status-ui.js"],
  ["speaking-loader.js", "src/features/speaking/speaking-loader.js"],
  ["vocabulary-loader.js", "src/features/vocabulary/vocabulary-loader.js"],
  ["project-hub-performance.js", "src/features/project-hub/project-hub-performance.js"],
  ["project-hub-core.js", "src/features/project-hub/project-hub-core.js"],
  ["project-hub-render.js", "src/features/project-hub/project-hub-render.js"],
  ["project-hub-actions.js", "src/features/project-hub/project-hub-actions.js"],
  ["turtlebot-plan-loader.js", "src/features/project-hub/turtlebot-plan-loader.js"],
  ["project-hub.css", "src/features/project-hub/project-hub.css"],
  ["turtlebot-card-art.css", "src/features/project-hub/turtlebot-card-art.css"],
  ["turtlebot4-card-background.webp", "src/features/project-hub/turtlebot4-card-background.webp"],
  ["app-icon-64.png", "src/assets/icons/app-icon-64.png"],
  ["app-icon-192.png", "src/assets/icons/app-icon-192.png"],
  ["joy-blue-icon.png", "src/assets/icons/joy-blue-icon.png"],
  ["joy-web-favicon.svg", "src/assets/icons/joy-web-favicon.svg"],
  ["wolf-mark.svg", "src/assets/icons/wolf-mark.svg"],
  ["site.webmanifest", "src/pwa/site.webmanifest"],
  ["sw.js", "src/pwa/sw.js"],
  ["modules", "src/features"],
  ["sale-fonts", "src/assets/fonts/nunito"],
];

const syntaxChecks = [
  "worker/shared/http.js",
  "worker/shared/schema.js",
  "worker/shared/session.js",
  "worker/dashboard-data.js",
  "worker/task-reminders.js",
  "worker/reminder-delivery.js",
  "worker/push.js",
  "worker/push-subscription-cleanup.js",
  "worker/sale-viewing-create.js",
  "worker/router.js",
  "worker/ielts-core.js",
  "worker/task-delete.js",
  "worker/task-english.js",
  ...dashboardAppSourceFiles,
  "src/pages/sale/room-summary.js",
  "src/features/sales/sale-appointment.js",
  "src/features/sales/sales-assistant.js",
  "src/features/finance/finance-amount-core.js",
  "src/features/weather/weather-rain.js",
  "src/features/tasks/task-english.js",
  "src/features/tasks/task-reminders-events.js",
  "src/features/tasks/task-reminders.js",
  "src/features/notifications/push-notifications.js",
  "src/features/notifications/weather-status-ui.js",
  "src/features/speaking/speaking-loader.js",
  "src/features/vocabulary/vocabulary-loader.js",
  "src/features/project-hub/project-hub-performance.js",
  "src/features/project-hub/project-hub-core.js",
  "src/features/project-hub/project-hub-render.js",
  "src/features/project-hub/project-hub-actions.js",
  "src/features/project-hub/turtlebot-plan-loader.js",
  "project-data/turtlebot4/project-current-state.js",
  "src/features/ielts/card.js",
  "src/features/ielts/core-model.js",
  "src/features/ielts/core-ui.js",
  "src/features/ielts/core-actions.js",
  "src/pwa/sw.js",
  "scripts/build.mjs",
  "scripts/build-finance-bundle.mjs",
  "scripts/deploy-clean-main.mjs",
  "scripts/run-feature-tests.mjs",
  "scripts/validate-ielts-sources.mjs",
];

const created = [];
const generated = [];

async function inspect(path) {
  try {
    return await lstat(path);
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

async function prepareDashboardCompatibilitySource() {
  const target = resolve(root, "src/pages/dashboard/app.js");
  const existing = await inspect(target);
  if (existing) {
    const content = await readFile(target, "utf8").catch(() => "");
    if (!content.startsWith(dashboardCompatibilityMarker)) {
      throw new Error("Canonical dashboard app.js must not be committed; edit the app-* modules instead.");
    }
    await rm(target, { force: true });
  }

  const parts = await Promise.all(
    dashboardAppSourceFiles.map((path) => readFile(resolve(root, path), "utf8")),
  );
  await writeFile(target, `${dashboardCompatibilityMarker}\n${parts.join("\n\n")}\n`);
  generated.push(target);
}

async function prepareCompatibilityLink(legacyPath, sourcePath) {
  const legacy = resolve(root, legacyPath);
  const source = resolve(root, sourcePath);
  const existing = await inspect(legacy);

  if (existing && !existing.isSymbolicLink()) {
    throw new Error(
      `Compatibility path ${legacyPath} already exists as a real file or directory. `
      + "Move or remove it before running the test suite.",
    );
  }

  if (existing) {
    // A previous interrupted test run may have left this managed symlink behind.
    await rm(legacy, { recursive: true, force: true });
  }

  await mkdir(dirname(legacy), { recursive: true });
  const target = relative(dirname(legacy), source) || ".";
  const type = legacyPath === "modules" || legacyPath === "sale-fonts" ? "dir" : "file";
  await symlink(target, legacy, type);
  created.push(legacy);
}

function runNode(args) {
  const child = spawn(process.execPath, args, { cwd: root, stdio: "inherit" });
  return new Promise((resolveExit, reject) => {
    child.once("error", reject);
    child.once("exit", (code, signal) => {
      if (signal) reject(new Error(`Test process ended with signal ${signal}`));
      else resolveExit(code ?? 1);
    });
  });
}

try {
  await prepareDashboardCompatibilitySource();

  for (const [legacyPath, sourcePath] of compatibilityPaths) {
    await prepareCompatibilityLink(legacyPath, sourcePath);
  }

  for (const path of syntaxChecks) {
    const exitCode = await runNode(["--check", path]);
    if (exitCode !== 0) {
      process.exitCode = exitCode;
      break;
    }
  }

  if (!process.exitCode) process.exitCode = await runNode(["--test"]);
} finally {
  await Promise.allSettled(
    created.reverse().map((path) => rm(path, { recursive: true, force: true })),
  );
  await Promise.allSettled(
    generated.reverse().map((path) => rm(path, { force: true })),
  );
}
